name: "Issue to JSON"

on:
  issues:
    types:
      - closed

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Issue Data
        id: extract
        run: |
          echo "Extracting issue data..."
          
          KEYWORD=$(echo "${{ github.event.issue.body }}" | grep -A1 "### Keyword" | tail -n1 | xargs)
          TABOO_WORDS=$(echo "${{ github.event.issue.body }}" | grep -A1 "### Taboo Words" | tail -n1 | tr ',' '\n' | sed 's/^ \+//g' | jq -R . | jq -s . | tr -d '\n')
          CATEGORY=$(echo "${{ github.event.issue.body }}" | grep -A1 "### Category" | tail -n1 | xargs)
          SOURCE_LANGUAGE=$(echo "${{ github.event.issue.body }}" | grep -A1 "### Source Language" | tail -n1 | xargs)
          DESTINATION_LANGUAGE=$(echo "${{ github.event.issue.body }}" | grep -A1 "### Destination Language" | tail -n1 | xargs)
          DESCRIPTION=$(echo "${{ github.event.issue.body }}" | grep -A1 "### Description" | tail -n1 | xargs)
          
          echo "KEYWORD=$KEYWORD" >> $GITHUB_ENV
          echo "TABOO_WORDS=$TABOO_WORDS" >> $GITHUB_ENV
          echo "CATEGORY=$CATEGORY" >> $GITHUB_ENV
          echo "SOURCE_LANGUAGE=$SOURCE_LANGUAGE" >> $GITHUB_ENV
          echo "DESTINATION_LANGUAGE=$DESTINATION_LANGUAGE" >> $GITHUB_ENV
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

      - name: Update cards.json
        run: |
          echo "Updating cards.json..."
          FILE=cards.json
          if [ ! -f "$FILE" ]; then
            echo '{ "keywords": [] }' > $FILE
          fi

          jq ".keywords += [{\"keyword\": \"$KEYWORD\", \"category\": \"$CATEGORY\", \"taboo_words\": $TABOO_WORDS, \"source_language\": \"$SOURCE_LANGUAGE\", \"destination_language\": \"$DESTINATION_LANGUAGE\", \"description\": \"$DESCRIPTION\"}]" $FILE > temp.json && mv temp.json $FILE

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add cards.json
          git commit -m "Update cards.json with closed issue #${{ github.event.issue.number }}"
          git push
